# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-18 07:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_auto_20180418_0003'),
    ]

    operations = [
        migrations.RenameField(
            model_name='choice',
            old_name='Answer',
            new_name='choice',
        ),
        migrations.AddField(
            model_name='questions',
            name='pub_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name=b'date published'),
        ),
        migrations.AddField(
            model_name='questions',
            name='question',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='choice',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Questions'),
        ),
    ]
